dubbo:
  application:
    name: dubbo-consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:21810
  consumer:
    #为整个消费方添加启动不检查提供方服务是否正常
    check: false
    # 重试次数
    retries: 3
    # 超时时间
    timeout: 30000

    # 调用失败时的容错设置 cluster=failover org.apache.dubbo.rpc.cluster.Cluster
    cluster: failover

    # 负载均衡策略设置 org.apache.dubbo.rpc.cluster.LoadBalance
    loadbalance: shortestresponse

    # 静态打标
    tag: gray

server:
  port: 8082
